name: Deploy Bot with Conda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true

    - name: Check repo files
      run: |
        ls -la
        cat environment.yml

    - name: Install dependencies from environment.yml
      run: conda env update --file environment.yml --name base

    - name: Run bot
      run: python app.py
